import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  ar: {
    dir: 'rtl',
    lang: 'ar',
    nav: {
      menu: 'القائمة',
      journey: 'رحلتنا',
      reserve: 'احجز طاولة',
      contact: 'تواصل',
      order: 'اطلب الآن',
    },
    hero: {
      badge: 'موجة القهوة الثالثة | الرياض',
      headline1: 'نُقَدِّم لَكَ أَصَالَةَ',
      headline3: 'فِي كُلِّ قَطرَة',
      words: ['القَهوَة', 'الأَصَالَة', 'اللَّحظَة', 'التَّجرِبَة'],
      sub: 'من مزارع جازان الخضراء إلى فنجانك — قهوة متخصصة تحمل عبق التراث السعودي وروح رؤية ٢٠٣٠ في كل لحظة.',
      orderNow: 'اطلب الآن',
      explore: 'استكشف القائمة',
      badges: ['V60 يومياً', 'حليب نباتي', 'حي النرجس', '٤.٩ تقييم'],
      stats: [{ num: '+٢٠٠', label: 'مزيج أصيل' }, { num: '٣', label: 'فروع الرياض' }, { num: '٩٨٪', label: 'رضا العملاء' }],
      today: 'اليوم',
      discover: 'اكتشف',
      floatLabel: 'إثيوبيا يرغاشيف',
      floatSub: 'Pour Over • اليوم',
    },
    menu: {
      tag: 'قائمة اليوم',
      title: 'كل كوب يحكي',
      titleHighlight: 'قصة',
      sub: 'بن مختار بعناية من أفضل مزارع العالم ومزارع جازان المحلية — يُحمّص أسبوعياً في مشرطنا',
      categories: ['الكل', 'Pour Over', 'لاتيه مميز', 'موسمي', 'بارد'],
      all: 'الكل',
      order: 'اطلب',
      sar: 'ريال',
      visitUs: 'تفضّل بزيارتنا',
      visitSub: 'حي النرجس، الرياض • يومياً ٧ص – ١٢م',
      fullMenu: 'عرض القائمة الكاملة',
    },
    journey: {
      tag: 'رحلة البن',
      title: 'من جبال جازان',
      titleHighlight: 'إلى فنجانك',
      sub: 'نؤمن بالشفافية الكاملة — كل حبة قهوة تحكي قصتها من اليوم الأول حتى آخر رشفة.',
      visionBadge: 'فخورون بهويتنا السعودية',
      visionSub: 'جزء من رؤية المملكة ٢٠٣٠ لتعزيز الهوية الوطنية',
      quote: 'القهوة ليست مشروباً — إنها لحظة تأمل في عالم لا يتوقف',
      quoteBy: '— فريق قَطرَة',
    },
    reservation: {
      tag: 'احجز طاولتك',
      title: 'لحظتك تستحق',
      titleHighlight: 'المكان المثالي',
      policy: 'سياسة الحجز:',
      policySub: 'إلغاء مجاني قبل الموعد بـ٢ ساعة. بعد التأكيد، يُرجى الحضور في الموعد المحدد للحفاظ على تجربة الجميع ✨',
      step1: 'الموعد والضيوف',
      step2: 'اختر المنطقة',
      guests: 'عدد الضيوف',
      date: 'اختر التاريخ',
      time: 'الوقت المناسب',
      today: 'اليوم',
      next: 'التالي — اختر المنطقة',
      name: 'اسمك الكريم',
      phone: 'رقم الجوال',
      confirm: 'تأكيد الحجز',
      confirmed: 'تم الحجز بنجاح!',
      another: 'حجز موعد آخر',
    },
    contact: {
      tag: 'تواصل معنا',
      title: 'لديك مشروع؟',
      titleHighlight: 'نحن نستمع',
      sub: 'سواء كنت تريد صفحة هبوط، موقعاً متكاملاً، أو نظام إدارة — تواصل معنا وسنرد خلال ٢٤ ساعة.',
      namePh: 'اسمك الكريم',
      emailPh: 'بريدك الإلكتروني',
      servicePh: 'نوع الخدمة',
      messagePh: 'أخبرنا عن مشروعك...',
      send: 'إرسال الرسالة',
      sending: 'جارٍ الإرسال...',
      successTitle: 'تم الإرسال بنجاح! 🎉',
      successSub: 'شكراً لتواصلك، سنرد عليك قريباً.',
      services: [
        { value: 'landing', label: 'صفحة هبوط' },
        { value: 'fullsite', label: 'موقع كامل' },
        { value: 'dashboard', label: 'لوحة إدارة' },
        { value: 'branding', label: 'هوية بصرية' },
        { value: 'other', label: 'أخرى' },
      ],
      info: [
        { icon: '📧', label: 'البريد', value: 'hamza.amimi.p@gmail.com' },
        { icon: '⚡', label: 'وقت الرد', value: 'خلال ٢٤ ساعة' },
        { icon: '🌍', label: 'نخدم', value: 'السعودية والخليج' },
      ],
    },
    dashboard: {
      tag: 'للمالك · نظام إدارة ذكي',
      title: 'أدِر مقهاك بذكاء',
      titleHighlight: 'من كل مكان',
      sub: 'منصة إدارة متكاملة مصممة خصيصاً لمقاهي الموجة الثالثة في السوق السعودي.',
      demoBtn: 'طلب عرض توضيحي',
      brochureBtn: 'تحميل الكتيب التعريفي',
      interested: 'مهتم بنظام إدارة قَطرَة؟',
      interestedSub: 'احصل على عرض توضيحي مجاني لمدة ٣٠ دقيقة مع أحد خبرائنا — بدون التزام',
      supports: 'يدعم:',
    },
    footer: {
      newsletter: 'اشترك في نشرتنا الأسبوعية',
      newsletterSub: 'طروحات حصرية، وصفات، وأحداث قادمة',
      subscribe: 'اشترك',
      emailPh: 'بريدك الإلكتروني',
      branches: 'فروعنا',
      copyright: '© ٢٠٢٦ قَطرَة للقهوة المتخصصة · جميع الحقوق محفوظة',
      privacy: 'سياسة الخصوصية',
      terms: 'الشروط والأحكام',
      tagline: 'نؤمن بأن كل قطرة قهوة هي قصة — من بذرة في جازان إلى فنجان في يديك.',
      quickLinks: 'روابط سريعة',
      about: 'عن قَطرَة',
      business: 'للأعمال',
      links: {
        quickLinks: ['قائمة المشروبات', 'احجز طاولة', 'اطلب الآن', 'رحلة البن', 'عروضنا'],
        about: ['قصتنا', 'القيم والمبادئ', 'فريقنا', 'الاستدامة', 'انضم إلينا'],
        business: ['نظام الإدارة', 'شراء امتياز', 'مورّدون', 'تواصل معنا', 'الدعم الفني'],
      },
    },
    order: {
      title: 'خصّص طلبك',
      subtitle: 'لأن كل تفصيل يهم',
      cart: 'السلة',
      cartSub: 'راجع طلبك',
      done: 'تم الطلب! 🎉',
      doneSub: 'شكراً لاختيارك قَطرَة',
      size: 'الحجم',
      milk: 'نوع الحليب',
      sweetness: 'مستوى الحلاوة',
      mode: 'طريقة الاستلام',
      notes: 'ملاحظات إضافية',
      notesPh: 'مثال: لا سكر، حليب إضافي...',
      next: 'التالي — مراجعة الطلب',
      confirmBtn: 'تأكيد الطلب عبر واتساب',
      whatsappTitle: 'تسجيل الدخول عبر واتساب',
      whatsappSub: 'أدخل رقمك لاستلام تأكيد الطلب فوراً',
      phonePh: '٥٠٠ ١٢٣ ٤٥٦',
      payment: 'طرق الدفع المقبولة',
      secure: '🔒 بياناتك آمنة ومحمية',
      qty: 'الكمية',
      total: 'الإجمالي',
      sar: 'ريال',
      orderOn: 'طلبك في الطريق!',
      orderSub: 'تم استلام طلبك بنجاح. ستصلك رسالة واتساب للتأكيد خلال لحظات ☕',
      whatsappConfirm: 'تأكيد عبر واتساب',
      summary: 'ملخص الطلب',
      product: 'المنتج',
      sizeLabel: 'الحجم',
      milkLabel: 'الحليب',
      sweetnessLabel: 'الحلاوة',
      modeLabel: 'الاستلام',
    },
    loader: 'نُحضّر تجربتك...',
    floatOrderBtn: '☕ اطلب الآن',
  },

  en: {
    dir: 'ltr',
    lang: 'en',
    nav: {
      menu: 'Menu',
      journey: 'Our Journey',
      reserve: 'Reserve a Table',
      contact: 'Contact',
      order: 'Order Now',
    },
    hero: {
      badge: 'Third Wave Coffee | Riyadh',
      headline1: 'We Serve You the',
      headline3: 'in Every Drop',
      words: ['Authenticity', 'Excellence', 'Moment', 'Experience'],
      sub: 'From the green farms of Jazan to your cup — specialty coffee carrying the essence of Saudi heritage and the spirit of Vision 2030.',
      orderNow: 'Order Now',
      explore: 'Explore Menu',
      badges: ['Daily V60', 'Plant Milk', 'Al Narjis', '4.9 Rating'],
      stats: [{ num: '+200', label: 'Unique Blends' }, { num: '3', label: 'Riyadh Branches' }, { num: '98%', label: 'Customer Satisfaction' }],
      today: 'Today',
      discover: 'Scroll',
      floatLabel: 'Ethiopia Yirgacheffe',
      floatSub: 'Pour Over • Today',
    },
    menu: {
      tag: "Today's Menu",
      title: 'Every Cup Tells a',
      titleHighlight: 'Story',
      sub: 'Beans carefully selected from the world\'s finest farms and local Jazan farms — roasted weekly in our roastery.',
      categories: ['All', 'Pour Over', 'Signature Latte', 'Seasonal', 'Cold'],
      all: 'All',
      order: 'Order',
      sar: 'SAR',
      visitUs: 'Visit Us',
      visitSub: 'Al Narjis, Riyadh • Daily 7AM – Midnight',
      fullMenu: 'View Full Menu',
    },
    journey: {
      tag: 'The Bean Journey',
      title: 'From the Mountains of Jazan',
      titleHighlight: 'to Your Cup',
      sub: 'We believe in full transparency — every coffee bean tells its story from day one until the last sip.',
      visionBadge: 'Proud of Our Saudi Identity',
      visionSub: 'Part of Saudi Vision 2030 to promote national identity',
      quote: 'Coffee is not a drink — it\'s a moment of reflection in a world that never stops',
      quoteBy: '— The Qatrah Team',
    },
    reservation: {
      tag: 'Book Your Table',
      title: 'Your Moment Deserves',
      titleHighlight: 'the Perfect Spot',
      policy: 'Booking Policy:',
      policySub: 'Free cancellation up to 2 hours before. After confirmation, please arrive on time to preserve everyone\'s experience ✨',
      step1: 'Date & Guests',
      step2: 'Choose Zone',
      guests: 'Number of Guests',
      date: 'Select Date',
      time: 'Preferred Time',
      today: 'Today',
      next: 'Next — Choose Zone',
      name: 'Your Name',
      phone: 'Phone Number',
      confirm: 'Confirm Booking',
      confirmed: 'Booking Confirmed!',
      another: 'Book Another Table',
    },
    contact: {
      tag: 'Get In Touch',
      title: 'Have a Project?',
      titleHighlight: "We're Listening",
      sub: 'Whether you need a landing page, a full website, or a management system — reach out and we\'ll respond within 24 hours.',
      namePh: 'Your Full Name',
      emailPh: 'Your Email Address',
      servicePh: 'Service Type',
      messagePh: 'Tell us about your project...',
      send: 'Send Message',
      sending: 'Sending...',
      successTitle: 'Message Sent! 🎉',
      successSub: "Thank you for reaching out. We'll get back to you soon.",
      services: [
        { value: 'landing', label: 'Landing Page' },
        { value: 'fullsite', label: 'Full Website' },
        { value: 'dashboard', label: 'Dashboard System' },
        { value: 'branding', label: 'Branding' },
        { value: 'other', label: 'Other' },
      ],
      info: [
        { icon: '📧', label: 'Email', value: 'hamza.amimi.p@gmail.com' },
        { icon: '⚡', label: 'Response Time', value: 'Within 24 hours' },
        { icon: '🌍', label: 'Serving', value: 'Saudi Arabia & Gulf' },
      ],
    },
    dashboard: {
      tag: 'Owner · Smart Management System',
      title: 'Manage Your Café Smartly',
      titleHighlight: 'From Anywhere',
      sub: 'An all-in-one management platform designed specifically for third-wave cafés in the Saudi market.',
      demoBtn: 'Request a Demo',
      brochureBtn: 'Download Brochure',
      interested: 'Interested in Qatrah Management?',
      interestedSub: 'Get a free 30-minute demo with one of our experts — no commitment required',
      supports: 'Supports:',
    },
    footer: {
      newsletter: 'Subscribe to Our Weekly Newsletter',
      newsletterSub: 'Exclusive offers, recipes, and upcoming events',
      subscribe: 'Subscribe',
      emailPh: 'Your email address',
      branches: 'Our Branches',
      copyright: '© 2026 Qatrah Specialty Coffee · All rights reserved',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      tagline: 'We believe every drop of coffee is a story — from a seed in Jazan to a cup in your hands.',
      quickLinks: 'Quick Links',
      about: 'About Qatrah',
      business: 'For Business',
      links: {
        quickLinks: ['Drinks Menu', 'Reserve a Table', 'Order Now', "Bean's Journey", 'Our Offers'],
        about: ['Our Story', 'Values & Principles', 'Our Team', 'Sustainability', 'Join Us'],
        business: ['Management System', 'Franchise', 'Suppliers', 'Contact Us', 'Technical Support'],
      },
    },
    order: {
      title: 'Customize Your Order',
      subtitle: 'Because every detail matters',
      cart: 'Cart',
      cartSub: 'Review your order',
      done: 'Order Placed! 🎉',
      doneSub: 'Thank you for choosing Qatrah',
      size: 'Size',
      milk: 'Milk Type',
      sweetness: 'Sweetness Level',
      mode: 'Pickup Method',
      notes: 'Additional Notes',
      notesPh: 'e.g. no sugar, extra milk...',
      next: 'Next — Review Order',
      confirmBtn: 'Confirm via WhatsApp',
      whatsappTitle: 'Login with WhatsApp',
      whatsappSub: 'Enter your number to receive order confirmation instantly',
      phonePh: '500 123 456',
      payment: 'Accepted Payment Methods',
      secure: '🔒 Your data is safe & secure',
      qty: 'Quantity',
      total: 'Total',
      sar: 'SAR',
      orderOn: 'Your Order is on the Way!',
      orderSub: 'Order received. You\'ll get a WhatsApp confirmation in moments ☕',
      whatsappConfirm: 'Confirm via WhatsApp',
      summary: 'Order Summary',
      product: 'Product',
      sizeLabel: 'Size',
      milkLabel: 'Milk',
      sweetnessLabel: 'Sweetness',
      modeLabel: 'Pickup',
    },
    loader: 'Preparing your experience...',
    floatOrderBtn: '☕ Order Now',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('ar')
  const t = translations[language]
  const toggle = () => setLanguage(l => l === 'ar' ? 'en' : 'ar')

  return (
    <LanguageContext.Provider value={{ language, t, toggle }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
